### ISSUE TITLE
Generate Meta Split programatically

### ISSUE THREAD

**Issue by noahott** [lucatume/cmb2-meta-split#3]
I'm using WP All import to import a bunch of posts. I'd like to have the import automatically generate the split post meta when it is done, but I can't get this to work.

Do you know how it would be possible to trigger this programmatically? I've tried calling wp_update_post() and do_action('save_post', $post_id, $post, true) but neither of these methods end up triggering CMB2_Meta_Split->met_save(). 

When I manually click the "update" button when editing a post the meta split data is generated correctly.

I appreciate any help or advice you can give.

**Comment by noahott** [comment]
I figured this out. It appears CMB2 does a number of checks that ensure the hooks only run when a users saves a post from the edit page directly, but I can call meta_save() after recreating the arguments like this:

`$cmb2_field = cmb2_get_field('metabox_id', 'field_meta_key', $post_id, 'post');
			$args = [
				'type' => 'post',
				'id' => $post_id,
				'field_id' => 'field_meta_key',
				'repeat' => TRUE,
				'single' => true,
				'value' => $data_to_save,
				'group' => true,
			];
			$field_args = $cmb2_field->args;
			\CMB2_Meta_Split::instance()->meta_save(null, $args, $field_args);`

**Comment by lucatume** [comment]
@noahott Thanks for coming back to this and updating it. I was out and came back to the best kind of issue: the one that solves itself.
